### ISSUE TITLE
Request for transfer: unassert-js organization

### ISSUE THREAD

**Issue by twada** [zoncoen/webpack-unassert-loader#2]
Hi , I've created a new organization [unassert-js](https://github.com/unassert-js) to help users finding related products easily, and I want you to transfer this project to unassert-js org.

If you agree with me, please see [about repository transfers](https://help.github.com/articles/about-repository-transfers/) for details. If you do not want to transfer, it's no problem at all ;)

Thanks!

**Comment by zoncoen** [comment]
I agree with you. I'll transfer this repository!

**Comment by zoncoen** [comment]
@twada Would you add me to unassert-js organizer as a collaborator for transferring repository?

**Comment by twada** [comment]
@zoncoen Thanks! && Invited! 😃

**Comment by zoncoen** [comment]
Thanks! I transferred this repository!

**Comment by twada** [comment]
Thank you! 🎉
